# Generated by Django 2.2.4 on 2019-08-12 18:13

import apps.common.fields
import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', django.contrib.postgres.fields.citext.CIEmailField(error_messages={'unique': 'That email address is already taken.'}, max_length=254, unique=True, verbose_name='Email')),
                ('phone', apps.common.fields.PhoneField(blank=True, default='', error_messages={'unique': 'That phone number is already taken.'}, max_length=13, unique=True, verbose_name='Phone')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
