# Generated by Django 2.2.4 on 2019-08-11 19:40

from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        CITextExtension()
    ]
